### ISSUE TITLE
Build fails with version 2.3.0

### ISSUE THREAD

**Issue by kingtosh** [laobamac/OCLP-Mod#2]
I installed version 2.3.0 and it fails when I build it after setting it all up.

**Comment by kingtosh** [comment]
> Do you have some screenshots?I tested the .pkg file and didn't find errors.

Here is the error message

Building Configuration on model: iMac19,2
Creating build folder

- Adding OpenCore v1.0.1 RELEASE
- Adding config.plist for OpenCore
- Adding Lilu.kext 1.6.8
- Adding 4K/5K Display Patch
- Enabling Boot Logo patch
- Found Wireless Device 14E4:4464
- Found dGPU (1): 1002:67EF
- Found GFX0 Device Path: PciRoot(0x0)/Pci(0x1,0x0)/Pci(0x0,0x0)
- Found GPU Arch: Archs.Polaris
- Adding SATA Hibernation Patch
- Fixing PCIe Storage Controller (1) reporting
- Fixing PCIe Storage Controller (2) reporting
- Fixing PCIe Storage Controller (3) reporting
- Fixing PCIe Storage Controller (4) reporting
- Fixing PCIe Storage Controller (5) reporting
- Fixing PCIe Storage Controller (6) reporting
- Fixing PCIe Storage Controller (7) reporting
- Found 3rd Party NVMe SSD (1): 1987:5016
- Found NVMe (0) at PciRoot(0x0)/Pci(0x1b,0x0)/Pci(0x0,0x0)
- Adding NVMeFix.kext 1.1.1
- Found 3rd Party NVMe SSD (2): 1987:5012
- Found NVMe (1) at PciRoot(0x0)/Pci(0x1c,0x4)/Pci(0x0,0x0)/Pci(0x1,0x0)/Pci(0x0,0x0)/Pci(0x1,0x0)/Pci(0x0,0x0)
- Adding ipc_control_port_options=0 to boot-args
- Adding AutoPkgInstaller.kext 1.0.4
- Setting SIP value to: 0xfff
- Allowing FileVault on Root Patched systems
- Enabling KC UUID mismatch patch
- Adding RSRHelper.kext 1.0.2
- Disabling AMFI
- Adding CSLVFixup.kext 2.6.1
- Adding EFICheckDisabler.kext 
- Enabling Verbose boot
- Adding OpenCanopy GUI
An internal error occurred while building:

Traceback (most recent call last):
  File "opencore_legacy_patcher/wx_gui/gui_build.py", line 142, in _build
  File "opencore_legacy_patcher/efi_builder/build.py", line 52, in __init__
  File "opencore_legacy_patcher/efi_builder/build.py", line 161, in _build_opencore
  File "opencore_legacy_patcher/efi_builder/build.py", line 85, in _build_efi
  File "opencore_legacy_patcher/efi_builder/misc.py", line 39, in __init__
  File "opencore_legacy_patcher/efi_builder/misc.py", line 56, in _build
  File "opencore_legacy_patcher/efi_builder/misc.py", line 357, in _general_oc_handling
  File "shutil.py", line 431, in copy
  File "shutil.py", line 256, in copyfile
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/zk/4k_rpf9j5fxgrm9yjncffz140000gn/T/tmp28z9mp23/payloads/Icon/Resources.zip'
![スクリーンショット 2024-11-14 23 07 48](https://github.com/user-attachments/assets/0a5b0c04-b04b-4b98-9ee3-15f2e76dd188)

**Comment by laobamac** [comment]
The problem had been repaired,see this [commit:ee5ea73](https://github.com/laobamac/OCLP-Mod/commit/ee5ea7393f643377707367316db78b5ab796479d) and 2.3.0 OCLP-Mod [Release/2.3.2](https://github.com/laobamac/OCLP-Mod/releases/tag/2.3.2)
